import { getCurrencyName, getSign } from "@/constants/commonfunctions";
const currency_name = getCurrencyName();
export const ENGLISH_LANG: Record<string, string> = {
  WELCOME: "Welcome",
  WHY_BOOK_US_HEAD: "Why Book With Us",
  WHY_BOOK_US_DESC: "Here to guide you through your challenges",
  WHY_BOOK_US_HEAD_1: "India’s No.1",
  WHY_BOOK_US_DESC_1: "India’s largest and most reliable chadhava platform.",
  WHY_BOOK_US_HEAD_2: "Temple Prasad",
  WHY_BOOK_US_DESC_2:
    "3L+ prasad boxes shipped directly from temples.",
  WHY_BOOK_US_HEAD_3: "2L+ Devotees",
  WHY_BOOK_US_DESC_3: "Trusted by 2 lakh+ devotees globally.",
  WHY_BOOK_US_HEAD_4: "Temple Partnerships",
  WHY_BOOK_US_DESC_4: "Partnered with senior priests from 50+ temples across India.",
  UPCOMING_PUJA_HEAD: "Upcoming Puja",
  UPCOMING_PUJA_SUBHEAD:
    "Experience sacred pujas from trusted temples—personalized rituals, video proof & prasad at your doorstep.",
  UPCOMING_PUJA_DESC:
    "A spiritual ritual to seek blessings, and positive energy",
  EXPLORE_MORE_PUJA: "Explore more puja",
  EXPLORE_MORE_CHADHAVA: "Explore more chadhava",
  VIEW_ALL: "View All",
  UPCOMING_CHADHAVA_HEAD: "Upcoming Chadhava",
  UPCOMING_CHADHAVA_SUBHEAD:
    "Experience sacred pujas from trusted temples—personalized rituals, video proof & prasad at your doorstep.",
  UPCOMING_CHADHAVA_DESC: "A devotional offering to seek blessings and peace",
  HOW_WORK_HEAD: "How it works?",
  HOW_WORK_HEAD_1: "Offerings",
  HOW_WORK_DESC_1:
    "Claim your blessing package and choose your Chadhava options",
  HOW_WORK_HEAD_2: "Details",
  HOW_WORK_DESC_2: "Fill name and gotra and pay dakshina",
  HOW_WORK_HEAD_3: "Vidhi",
  HOW_WORK_DESC_3: "Pandit ji will offer the chadhawa on the said date",
  HOW_WORK_HEAD_4: "Blessings",
  HOW_WORK_DESC_4: "Receive Video on Whatsapp in 2-3 days",
  FAQ_HEAD: "Frequently asked questions (FAQs)",
  FAQ_QUES_1: " What will be done in this Puja?",
  FAQ_ANS_1: `Our pandit ji's conducting pujas at the famous temples have
          exceptional knowledge and experience in Vedic rituals. Every puja
          through Ghar Mandir is always conducted in your name and gotra, as
          mentioned in our Vedas. Our pandit ji will perform your Puja with the
          right mantras and rituals mentioned in the ancient scriptures. After
          completing the Puja, pandit ji will pray for the well-being of your
          family and your success.`,
  FAQ_QUES_2: "How will I know the Puja has been done?",
  FAQ_ANS_2: `Ghar Mandir is a trusted devotional brand where we perform every puja
          as per Sanatan Dharma. Our experienced pandits of the temple will
          meticulously perform the Vedic rituals in your name and gotra and pray
          for your happiness and success. After the completion of the rituals,
          we will share a personalised video of the Puja to your Whatsapp
          number. Additionally, the prasad (if chosen) from the puja will be
          delivered to your home.`,
  FAQ_QUES_3: "I don't know my Gotra, what should I do?",
  FAQ_ANS_3: `We would first suggest you to consult elders in your family to gather
          more information about your Gotra. If at all, no one in your family
          remembers the Gotra information, you can follow the guidance of the
          Shastras. As per the Shastras, if someone doesn't know their Gotra
          they can consider their Gotra as Kashyap Gotra. So you can mention
          Kashyap Gotra in your sankalp form while completing the booking and
          proceed with your booking.`,
  BLESSED_MOMENTS_VIDEO_HEAD: "Blessed Moments from Devotees",
  DIVINE_EXPERIENCE: "Past Pooja Videos",
  DEVOTEE_REVIEWS: "Devotees Reviews",
  JOIN_OUR_DIVINE_COMMUNITY: "Join our Divine Community",
  SPIRITUAL_BANNER_HEAD: "Confused about which puja to choose?",
  SPIRITUAL_BANNER_SUBHEAD_1: "Need guidance to find the right ritual?",
  SPIRITUAL_BANNER_SUBHEAD_2:
    "We're here to help you make the right spiritual choice.",
  SPIRITUAL_BANNER_BTN: "Get Spiritual help",
  SELECT_PACKAGE: "Select Package",
  WHY_PERFORM_THIS_PUJA: "Why Perform This Puja",
  ABOUT_TEMPLE: "About Temple",
  PUJA_PERFORM_BY: "Puja performed by",
  PUJA_NO_LONGER_AVAILABLE: "Puja no longer available",
  UNAVAILABLE: "Unavailable",
  PACKAGE_PRICE: "Package price",
  CHOOSE_YOUR_PACKAGE: "Choose your package",
  WHAT_WILL_YOU_GET: "What You'll Get",
  WHY_PERFORM_HEAD_1: "Offering at the temple in your name",
  WHY_PERFORM_DESC_1:
    "Your puja will be performed in your name and gotra, ensuring a truly personalized ritual. Our priests follow Vedic traditions to invoke blessings specifically for you and your family.",
  WHY_PERFORM_HEAD_2: "Receive Your Puja Video on WhatsApp",
  WHY_PERFORM_HEAD_3: "Prasad from temple delivered to your home",

  ADD_PRASAD: "Add Prasad",
  ADD_CHADHAVA_IN_THALI: "Add chadhawa in thali",
  CHADHAVA_NO_LONGER_AVAILABLE: "Chadhava no longer available",
  ADD_TO_YOUR_THALI: "Add to your thali",
  CHOOSE_YOUR_CHADHAVA: "Choose your chadhava",
  ADD_CHADHAVA: "Add Chadhava",
  ADD_OFFERINGS: "Add offerings",
  ADD_PLUS: "Add+",
  ONWARDS: "onwards",
  OUT_OF_STOCK: "Out of stock",
  CHADHAVA_SELECTED: "Chadhava selected",
  ADD_MORE_OFFERINGS: "Add more offerings",
  TOTAL: "Total",
  ADD_YOUR_SANKALP: "Add your sankalp",
  PACKAGE_OFFERINGS: "Package offerings",
  CHECKOUT: "Checkout",
  TOTAL_PRICE: "Total price",
  EDIT_PACKAGE: "Edit Package",
  SELECTED: "selected",
  PUJA_SELECTED: "Puja selected",
  PRASAD: "Prasad",
  AD_ONS: "Ad Ons",
  OFFERING_PRASAD_ERROR: "Please select at least one offering or prasad",
  PLZ_SELECT_PACKAGE: "Please select a package",
  YOUR_PUJA: "Your Puja",
  YOUR_CHADHAVA: "Your Chadhava",
  ARE_YOU_SURE_WANT_TO_REMOVE: "Are you sure want to remove this?",
  REMOVED_SUCCESSFULLY: "Removed successfully",
  REMOVE: "Remove",
  EDIT: "Edit",
  NO_PACKAGE: "No Package",

  ENTER_CONTACT_DETAILS: "Enter contact details",
  ENTER_YOUR_NAME: "Enter Your Name",
  WILL_BE_USED_FOR_SENDING_VIDEO_OF_SEVA:
    "Will be used for sending video of sewa",
  WILL_BE_RICTED_DURING_SEVA: "Will be recited during sewa",
  ADD_FAMILY_MEMBER: "Add Family Members ",
  MEMBER_PARTICIPATING: "Member participating",
  SEVA_PERFORM_BY_THIS_NAME: " Seva will be performed by this name",
  ADD_MEMBER_WITH_50_RUPEE: `Add a member for an additional charge of ${getSign()}${
    currency_name == "INR" ? "50" : "5"
  } per member`,
  ADD_PITRU_WITH_50_RUPEE: `Add a pitru for an additional charge of ${getSign()}${
    currency_name == "INR" ? "50" : "5"
  } per name`,
  ENTER_FAMILY_MEMBER_NAME: "Enter family member name",
  ADD_MEMBER: " +Add member",
  GOTRA_OF_MEBMBER: "Gotra of Member",
  ENTER_GOTRA: "Enter gotra",
  NOT_KNOW_GOTRA: "Don't know my gotra",
  ADDRESS: "Address",
  ADDRESS_DESC: "Prasad will be delivered on this address",
  STREET_ADDRESS: "Street Address",
  HOUSE_NUMBER_STREET_NAME: "House number and street name",
  POSTAL_CODE: "Postal Code",
  TOWN_CITY: "Town/City",
  ENTER_CITY: "Enter City",
  STATE_REGION: "State/Region",
  ENTER_STATE: "Enter State",
  MEMBER_SHDNT_EMPTY: "Member field should not be empty",
  MEMBER_SHDNT_EMPTY_EXCEED_20_CHAR:
    "Member name should not exceed 20 characters",
  NAME_SHDNT_EMPTY: "Name field should not be empty",

  POSTAL_CODE_ERROR: "Postal code must be 6 digits",
  SHDNT_EXCEED_20_CHAR: "should not exceed 80 characters",
  IS_REQUIRED: "is required",
  PHN_REQ: "Phone number is required",
  PHN_REQ_WARN: "Phone number must be 10 digits",
  "Street address": "Street address",
  "Postal Code": "Postal Code",
  "Town/City": "Town/City",
  City: "City",
  "State/Region": "State/Region",
  State: "State",
  CITY_NOT_FOUND: "City not found for this pincode",
  RECOMMENDED_CHADHAVA: "Recommended Chadhava",
  ALREADY_IN_CART: "Already Added. You can update and remove in cart",
  ADDED: "Added",
  HOME: "Home",
  PUJA: "Puja",
  CHADHAVA: "Chadhava",
  CONTACT_US: "Contact Us",
  SLOGAN: "Aapki shraddha, Hamari Jimmedari",
  QUICK_LINKS: "Quick Links",
  PARTICIPATE_NOW: "Participate Now",

  NEED_ASSISTANCE: "Need assistance for problems in your life?",
  GET_ASSISTANCE: "Get Assistance",
  COMPLETE_PROFILE: "Complete profile",
  COMPLETE_PROFILE_FOR_EXP:
    "Complete your profile for a smooth spiritual experience",
  BOOKINGS: "Bookings",
  PROFILE: "Profile",
  LOG_OUT: "Log Out",

  PROFILE_TITLE: "Profile",
  PROFILE_PICTURE: "Profile Picture",
  PERSONAL_DETAILS: "Personal Details",
  FAMILY_MEMBERS: "Family Members",
  SAVE_CHANGES: "Save Changes",
  CHANGE_PICTURE: "Change",
  NAME_REQUIRED: "Full name is required",
  EMAIL_REQUIRED: "Email is required",
  INVALID_EMAIL: "Invalid email format",
  PHONE_REQUIRED: "Phone number is required",
  INVALID_PHONE: "Invalid phone number format",
  BIRTHDATE_REQUIRED: "Birth date is required",
  GENDER_REQUIRED: "Gender is required",
  BIRTHPLACE_REQUIRED: "Place of Birth is required",
  BIRTHTIME_REQUIRED: "Time of birth is required",
  STREET_REQUIRED: "Street address is required",
  POSTALCODE_REQUIRED: "Postal code is required",
  INVALID_POSTALCODE: "Postal code must be 6 digits",
  CITY_REQUIRED: "City is required",
  STATE_REQUIRED: "State is required",
  FAMILY_MEMBER_NAME_REQUIRED: "All family members must have a name",
  IMAGE_FILE_ERROR: "Please select an image file",
  IMAGE_UPLOAD_ERROR: "Failed to upload image",
  PROFILE_UPDATE_SUCCESS: "Profile updated successfully",

  ENTER_POSTAL_CODE: "Enter postal code",

  FULL_NAME: "Full Name",
  ENTER_FULL_NAME: "Enter full name",
  GOTRA: "Gotra",
  GENDER: "Gender",
  MALE: "Male",
  FEMALE: "Female",
  OTHER: "Other",
  MARITAL_STATUS: "Marital Status",
  MARRIED: "Married",
  UNMARRIED: "Unmarried",
  MOBILE_NUMBER: "Mobile Number",
  ENTER_MOBILE_NUMBER: "Enter mobile number",
  EMAIL: "Email",
  ENTER_EMAIL: "Enter email",
  BIRTH_DATE: "Birth Date",
  ENTER_BIRTH_DATE: "Enter birth date",
  PLACE_OF_BIRTH: "Place of Birth",
  ENTER_PLACE_OF_BIRTH: "Enter place of birth",
  TIME_OF_BIRTH: "Time of Birth",
  ANNIVERSARY_DATE: "Anniversary date",
  ENTER_ANNIVERSARY_DATE: "Enter anniversary date",

  GET_IN_TOUCH: "Get in touch",
  CONTACT_DESC: "We'd love to hear from you. Please fill out this form.",
  PHONE_NUMBER: "Phone number",
  ENTER_PHONE_NUMBER: "99999 99999",
  QUERY_TYPE: "Query type",
  SELECT_QUERY_TYPE: "Select a query type",
  PREFERRED_TIME: "Preferred time to contact",
  SELECT_TIME_SLOT: "Select time slot",
  MESSAGE_DETAIL: "Your Message/Query detail",
  ENTER_MESSAGE: "Write....",
  SUBMIT: "Submit",
  SUBMITTING: "Submitting...",
  REPLY_TIME: "*Our team will revert within 24 hours",

  ACTIVE_PAST_PUJA: "Active & Past Puja",
  PRASAD_STATUS: "Prasad Status",
  PRASAD_PACKED: "Your prasad has been packed",
  NO_BOOKINGS_FOUND: "No bookings found!",
  SEARCH_PLACEHOLDER: "Search by name, temple or booking ID",

  BEFORE_RITUAL: "Before you begin the ritual",
  RITUAL_TIP_1: "Bathe and wear clean clothes",
  RITUAL_TIP_2: "Be calm and devoted",
  RITUAL_TIP_3: "Keep the space and mind pure",
  RITUAL_TIP_4: "Follow the priest's guidance",
  MEMBERS_COUNT: "Members",
  ENTER_NAME: "Enter full name",
  SAVE_MEMBERS: "Save",
  MANTRAS: "Mantra Recommended",
  NO_MANTRAS: "No mantra recommended",
  PUJA_STARTED: "Puja Started",
  PUJA_ENDED: "Puja Ended",
  PUJA_COMPLETE: "Puja Complete",
  VIDEO_NOTE:
    "📌 Note: Your complete Seva video will be shared on WhatsApp within 2-3 days after the Chadhava.",
  MAX_LIMIT_REACHED: "The maximum limit has been reached.",
  MEMBERS_UPDATED: "Members updated successfully.",
  ADD: "Add",
  PACKAGE: "Package",
  DATE: "Date",
  TIME: "Time",
  TITHI: "Tithi",
  PRASAD_WILL_DISPATCH_ONCE_PUJA_DONE:
    "Prasad will be dispatched once the puja is done",
  TRACK_YOUR_PRASAD: "Track your Prasad",
  PUJA_WILL_PERFORM_BY: "Puja will be performed by",
  IMP_NOTICE:
    "Important Note: All updates for your Kamakhya Seva, including confirmations and video links, will be shared with you on WhatsApp through our official number: +91 7039858794.",
  PAY_NOW: "Pay now",
  PLZ_FILL_REQ_FIELD:
    "Please enter valid information in the highlighted fields.",
  NOT_AVAILABLE: "Not Available",
  NOT_AVAILABLE_DESC:
    "The information you're looking for is currently unavailable. Please check back later or contact support if you need immediate assistance.",
  NO_MATCHING_RESULT: "No Matching Results",
  NO_MATCHING_RESULT_DESC:
    "We couldn't find any items matching your search criteria. Try different keywords, adjust your filters, or browse our full collection.",
  NOT_LOGGEDIN: "Not Loggedin!",
  NOT_LOGGEDIN_DESC_1: "Please log in to view and manage your cart items.",
  NOT_LOGGEDIN_DESC_2:
    "Already have an account? Sign in or create one to start shopping!",
  LOGIN_HERE: "Login Here",

  LOGIN_TITLE: "Fill your login details",
  MOBILE_TITLE: "Enter your mobile number",
  MOBILE_SUBTITLE:
    "Booking updates, Puja photos, videos & details will be shared on WhatsApp on below number",
  NAME_TITLE: "Enter Your Name",
  NAME_PLACEHOLDER: "Add full name",
  OTP_TITLE: "Enter OTP",
  OTP_SUBTITLE: "We've sent a 6-digit OTP to your mobile number",
  VERIFY: "Verify & Continue",
  RESEND_OTP: "Resend OTP",
  RESEND_TIMER: "Resend OTP",
  LOGIN_SUCCESS: "Login successful",
  OTP_ERROR: "Please enter valid OTP",
  MOBILE_REQUIRED: "Mobile number is required",
  INVALID_MOBILE: "Please enter a valid 10-digit mobile number",
  SHORT_NAME: "Name must be at least 3 characters",
  INVALID_NAME: "Name should contain only letters and spaces",
  OTP_REQUIRED: "OTP is required",
  INVALID_OTP: "OTP must be 6 digits",
  SEARCH_BOOKING: "Search Bookings",
  NO_OFFERINGS_FOUND: "No Offerings Found",
  NO_OFFERINGS_FOUND_DESC:
    "There are currently no offerings available for this puja. Please check back later.",
  ENTER_WHATSAPP_DETAILS: "Enter Whatsapp Number",

  EMPTY_CART_HEAD: "Your Cart is Empty",
  EMPTY_CART_DESC:
    "Looks like you haven't added any items yet. Start shopping to fill your cart!",
  BRW_PROD: "Browse Products",
  DATA_NOT_FOUND: "No Data Found",
  DATA_NOT_FOUND_DESC:
    "We couldn't find any matching results. Try adjusting your search or filters.",
  TRY_NOW: "Try Again",

  PHN_DIGITS_ONLY: "Phone number must contain only digits",
  ABOUT_US: "About Us",
  HOW_GM_STARTED: "How Ghar Mandir started",
  CONTENT_1:
    "Founded by IIM Calcutta, Bain, McKinsey and Bank of America alums",
  CONTENT_2:
    "“Ghar Mandir” is on a mission to revolutionize the way Indians pray!",
  CONTENT_3:
    "With an extensive network of renowned priests and temples, Ghar Mandir offers a seamless experience for booking personalized virtual pujas and a host of other services.",

  CONTENT_4: "Meet the Co-Founders",
  CONTENT_5: "Know more about the people behind Ghar Mandir",

  DIVINE_JOURNEY_HEADING: "Our Divine Journey in Numbers",
  PUJA_CHADHAWA_OFFERED: "Puja and Chadhava offered",
  PUJA_CHADHAWA_COUNT: "6,00,000+",
  PUJA_CHADHAWA_DESC:
    "For years, we've delivered pujas and chadhawas with faith and sincerity trusted by thousands.",
  TRUSTED_USERS: "Trusted Users",
  TRUSTED_USERS_COUNT: "2,00,000+",
  TRUSTED_USERS_DESC:
    "Serving pujas and chadhawas for years, delivering blessings and tradition to your doorstep.",
  ASSOCIATED_TEMPLES: "Associated number of Temples",
  ASSOCIATED_TEMPLES_COUNT: "50+",
  ASSOCIATED_TEMPLES_DESC:
    "Bringing you pujas and chadhawas from trusted temples, delivered with devotion for years.",
  ROOTED_IN_HINDUISM: "Rooted in Hinduism",
  WHO_WE_ARE_HEADING: "Who We Are",
  WHO_WE_ARE_DESC:
    "We are a team devoted to preserving and sharing the essence of Hindu culture through sacred rituals, offerings, and meaningful practices. Rooted in tradition, driven by devotion.",
  OUR_PHILOSOPHY_HEADING: "Our Philosophy",
  OUR_PHILOSOPHY_DESC:
    "We believe that spirituality is a way of life guided by dharma, shaped by karma, and nurtured through daily acts of devotion. Each puja, each chadhawa, is a step closer to inner peace and divine connection.",
  CULTURE_WE_CHERISH_HEADING: "Culture We Cherish",
  CULTURE_WE_CHERISH_DESC:
    "From ancient temples to everyday homes, Hinduism lives through its rituals, festivals, and values. We aim to make these timeless traditions accessible and relevant in today's world.",
  DEVOTEES_THOUGHTS_HEADING: "Devotees Thoughts",
  DEVOTEE_1_COMMENT:
    "Main to Dhanya ho gai Hanuman Giri ka Prasad pakar Bajrangbali ki kripa aap logon Ko sada banaa Rahe aur aap logon ke dwara mujhmein per banaa Rahe bhakti- bhut dhanyvad 🙏🙏",
  DEVOTEE_1_NAME: "-Ruby Singh",
  DEVOTEE_2_COMMENT:
    "Jai Badri Vishal . Mai bahot bhagyshalali hu ki Ghar Mandir dwara Ayojit Badhidham Tulsi Chadhava Pooja ka Vidio Prapat huva Badri Pandittone Bahot acchi tarah Pooja karawaya hai. Muze khushi hai maine Pooja Chadhava mai bhag liya ,participat kiya Dhanyawad Ghar Mandir. Thanks a Lot",
  DEVOTEE_2_NAME: "-Sanjay Bajrang Channe",
  DEVOTEE_3_COMMENT:
    "Aap ki team ek bohot acha kaam kar rahi h .... Jo log door tirth nhi kar pate wo ghar bethe hi pooja karwa kar laabh uthate h .... aapka sab ka bohot bohot dhanyawad 🙏",
  DEVOTEE_3_NAME: "-Rajeev Nohwal",
  WE_ARE_LOOKING_HEADING: "We are looking for fellow builders",
  WE_ARE_LOOKING_SUBHEADING:
    "If you're driven to make an impact in India's fast-growing devotion-tech space, reach out:",
  HIRING_EMAIL: "recruit@gharmandir.in",
};
