import { getCurrencyName, getSign } from "@/constants/commonfunctions";
const currency_name = getCurrencyName();
export const HINDI_LANG: Record<string, string> = {
  WELCOME: "Welcome",
  WHY_BOOK_US_HEAD: "Why Book With Us",
  WHY_BOOK_US_DESC: "Here to guide you through your challenges",
  WHY_BOOK_US_HEAD_1: "India’s No.1",
  WHY_BOOK_US_DESC_1: "India’s largest and most reliable chadhava platform.",
  WHY_BOOK_US_HEAD_2: "Temple Prasad",
  WHY_BOOK_US_DESC_2:
    "3L+ prasad boxes shipped directly from temples.",
  WHY_BOOK_US_HEAD_3: "2L+ Devotees",
  WHY_BOOK_US_DESC_3: "Trusted by 2 lakh+ devotees globally.",
  WHY_BOOK_US_HEAD_4: "Temple Partnerships",
  WHY_BOOK_US_DESC_4:
    "Partnered with senior priests from 50+ temples across India.",
  UPCOMING_PUJA_HEAD: "Upcoming Puja",
  UPCOMING_PUJA_SUBHEAD:
    "Experience sacred pujas from trusted temples—personalized rituals, video proof & prasad at your doorstep.",
  UPCOMING_PUJA_DESC:
    "A spiritual ritual to seek blessings, and positive energy",
  EXPLORE_MORE_PUJA: "Explore more puja",
  EXPLORE_MORE_CHADHAVA: "Explore more chadhava",
  VIEW_ALL: "View All",
  UPCOMING_CHADHAVA_HEAD: "Upcoming Chadhava",
  UPCOMING_CHADHAVA_SUBHEAD:
    "Experience sacred pujas from trusted temples—personalized rituals, video proof & prasad at your doorstep.",
  UPCOMING_CHADHAVA_DESC: "A devotional offering to seek blessings and peace",
  HOW_WORK_HEAD: "How it works?",
  HOW_WORK_HEAD_1: "Offerings",
  HOW_WORK_DESC_1:
    "Claim your blessing package and choose your Chadhava options",
  HOW_WORK_HEAD_2: "Details",
  HOW_WORK_DESC_2: "Fill name and gotra and pay dakshina",
  HOW_WORK_HEAD_3: "Vidhi",
  HOW_WORK_DESC_3: "Pandit ji will offer the chadhawa on the said date",
  HOW_WORK_HEAD_4: "Blessings",
  HOW_WORK_DESC_4: "Receive Video on Whatsapp in 2-3 days",
  FAQ_HEAD: "Frequently asked questions (FAQs)",
  FAQ_QUES_1: " What will be done in this Puja?",
  FAQ_ANS_1: `Our pandit ji's conducting pujas at the famous temples have
          exceptional knowledge and experience in Vedic rituals. Every puja
          through Ghar Mandir is always conducted in your name and gotra, as
          mentioned in our Vedas. Our pandit ji will perform your Puja with the
          right mantras and rituals mentioned in the ancient scriptures. After
          completing the Puja, pandit ji will pray for the well-being of your
          family and your success.`,
  FAQ_QUES_2: "How will I know the Puja has been done?",
  FAQ_ANS_2: `Ghar Mandir is a trusted devotional brand where we perform every puja
          as per Sanatan Dharma. Our experienced pandits of the temple will
          meticulously perform the Vedic rituals in your name and gotra and pray
          for your happiness and success. After the completion of the rituals,
          we will share a personalised video of the Puja to your Whatsapp
          number. Additionally, the prasad (if chosen) from the puja will be
          delivered to your home.`,
  FAQ_QUES_3: "I don't know my Gotra, what should I do?",
  FAQ_ANS_3: `We would first suggest you to consult elders in your family to gather
          more information about your Gotra. If at all, no one in your family
          remembers the Gotra information, you can follow the guidance of the
          Shastras. As per the Shastras, if someone doesn't know their Gotra
          they can consider their Gotra as Kashyap Gotra. So you can mention
          Kashyap Gotra in your sankalp form while completing the booking and
          proceed with your booking.`,
  BLESSED_MOMENTS_VIDEO_HEAD: "Blessed Moments from Devotees",
  DIVINE_EXPERIENCE: "Past Pooja Videos",
  DEVOTEE_REVIEWS: "Devotees Reviews",
  JOIN_OUR_DIVINE_COMMUNITY: "Join our Divine Community",
  SPIRITUAL_BANNER_HEAD: "Confused about which puja to choose?",
  SPIRITUAL_BANNER_SUBHEAD_1: "Need guidance to find the right ritual?",
  SPIRITUAL_BANNER_SUBHEAD_2:
    "We're here to help you make the right spiritual choice.",
  SPIRITUAL_BANNER_BTN: "Get Spiritual help",
  SELECT_PACKAGE: "Select Package",
  WHY_PERFORM_THIS_PUJA: "Why Perform This Puja",
  ABOUT_TEMPLE: "About Temple",
  PUJA_PERFORM_BY: "Puja performed by",
  PUJA_NO_LONGER_AVAILABLE: "Puja no longer available",
  UNAVAILABLE: "Unavailable",
  PACKAGE_PRICE: "Package price",
  CHOOSE_YOUR_PACKAGE: "Choose your package",
  WHAT_WILL_YOU_GET: "What You'll Get",
  WHY_PERFORM_HEAD_1: "Offering at the temple in your name",
  WHY_PERFORM_DESC_1:
    "Your puja will be performed in your name and gotra, ensuring a truly personalized ritual. Our priests follow Vedic traditions to invoke blessings specifically for you and your family.",
  WHY_PERFORM_HEAD_2: "Receive Your Puja Video on WhatsApp",
  WHY_PERFORM_HEAD_3: "Prasad from temple delivered to your home",

  ADD_PRASAD: "Add Prasad",
  ADD_CHADHAVA_IN_THALI: "Add chadhawa in thali",
  CHADHAVA_NO_LONGER_AVAILABLE: "Chadhava no longer available",
  ADD_TO_YOUR_THALI: "Add to your thali",
  CHOOSE_YOUR_CHADHAVA: "Choose your chadhava",
  ADD_CHADHAVA: "Add Chadhava",
  ADD_OFFERINGS: "Add offerings",
  ADD_PLUS: "Add+",
  ONWARDS: "onwards",
  OUT_OF_STOCK: "Out of stock",
  CHADHAVA_SELECTED: "Chadhava selected",
  ADD_MORE_OFFERINGS: "Add more offerings",
  TOTAL: "Total",
  ADD_YOUR_SANKALP: "Add your sankalp",
  PACKAGE_OFFERINGS: "Package offerings",
  CHECKOUT: "Checkout",
  TOTAL_PRICE: "Total price",
  EDIT_PACKAGE: "Edit Package",
  SELECTED: "selected",
  PUJA_SELECTED: "Puja selected",
  PRASAD: "Prasad",
  AD_ONS: "Ad Ons",
  OFFERING_PRASAD_ERROR: "Please select at least one offering or prasad",
  PLZ_SELECT_PACKAGE: "Please select a package",
  YOUR_PUJA: "Your Puja",
  YOUR_CHADHAVA: "Your Chadhava",
  ARE_YOU_SURE_WANT_TO_REMOVE: "Are you sure want to remove this?",
  REMOVED_SUCCESSFULLY: "Removed successfully",
  REMOVE: "Remove",
  EDIT: "Edit",
  NO_PACKAGE: "No Package",

  ENTER_CONTACT_DETAILS: "Enter contact details",
  ENTER_YOUR_NAME: "Enter Your Name",
  WILL_BE_USED_FOR_SENDING_VIDEO_OF_SEVA:
    "Will be used for sending video of sewa",
  WILL_BE_RICTED_DURING_SEVA: "Will be recited during sewa",
  ADD_FAMILY_MEMBER: "Add Family Members ",
  MEMBER_PARTICIPATING: "Member participating",
  SEVA_PERFORM_BY_THIS_NAME: " Seva will be performed by this name",
  ADD_MEMBER_WITH_50_RUPEE: `Add a member for an additional charge of ${getSign()}${
    currency_name == "INR" ? "50" : "5"
  } per member`,
  ADD_PITRU_WITH_50_RUPEE: `Add a pitru for an additional charge of ${getSign()}${
    currency_name == "INR" ? "50" : "5"
  } per name`,
  ENTER_FAMILY_MEMBER_NAME: "Enter family member name",
  ADD_MEMBER: " +Add member",
  GOTRA_OF_MEBMBER: "Gotra of Member",
  ENTER_GOTRA: "Enter gotra",
  NOT_KNOW_GOTRA: "Don't know my gotra",
  ADDRESS: "Address",
  ADDRESS_DESC: "Prasad will be delivered on this address",
  STREET_ADDRESS: "Street Address",
  HOUSE_NUMBER_STREET_NAME: "House number and street name",
  POSTAL_CODE: "Postal Code",
  TOWN_CITY: "Town/City",
  ENTER_CITY: "Enter City",
  STATE_REGION: "State/Region",
  ENTER_STATE: "Enter State",
  MEMBER_SHDNT_EMPTY: "Member field should not be empty",
  MEMBER_SHDNT_EMPTY_EXCEED_20_CHAR:
    "Member name should not exceed 20 characters",
  NAME_SHDNT_EMPTY: "Name field should not be empty",

  POSTAL_CODE_ERROR: "Postal code must be 6 digits",
  SHDNT_EXCEED_20_CHAR: "should not exceed 80 characters",
  IS_REQUIRED: "is required",
  PHN_REQ: "Phone number is required",
  PHN_REQ_WARN: "Phone number must be 10 digits",
  "Street address": "Street address",
  "Postal Code": "Postal Code",
  "Town/City": "Town/City",
  City: "City",
  "State/Region": "State/Region",
  State: "State",
  CITY_NOT_FOUND: "City not found for this pincode",
  RECOMMENDED_CHADHAVA: "Recommended Chadhava",
  ALREADY_IN_CART: "Already Added. You can update and remove in cart",
  ADDED: "Added",
  HOME: "Home",
  PUJA: "Puja",
  CHADHAVA: "Chadhava",
  CONTACT_US: "Contact Us",
  SLOGAN: "Aapki shraddha, Hamari Jimmedari",
  QUICK_LINKS: "Quick Links",
  PARTICIPATE_NOW: "Participate Now",

  NEED_ASSISTANCE: "Need assistance for problems in your life?",
  GET_ASSISTANCE: "Get Assistance",
  COMPLETE_PROFILE: "Complete profile",
  COMPLETE_PROFILE_FOR_EXP:
    "Complete your profile for a smooth spiritual experience",
  BOOKINGS: "Bookings",
  PROFILE: "Profile",
  LOG_OUT: "Log Out",

  PROFILE_TITLE: "Profile",
  PROFILE_PICTURE: "Profile Picture",
  PERSONAL_DETAILS: "Personal Details",
  FAMILY_MEMBERS: "Family Members",
  SAVE_CHANGES: "Save Changes",
  CHANGE_PICTURE: "Change",
  NAME_REQUIRED: "Full name is required",
  EMAIL_REQUIRED: "Email is required",
  INVALID_EMAIL: "Invalid email format",
  PHONE_REQUIRED: "Phone number is required",
  INVALID_PHONE: "Invalid phone number format",
  BIRTHDATE_REQUIRED: "Birth date is required",
  GENDER_REQUIRED: "Gender is required",
  BIRTHPLACE_REQUIRED: "Place of Birth is required",
  BIRTHTIME_REQUIRED: "Time of birth is required",
  STREET_REQUIRED: "Street address is required",
  POSTALCODE_REQUIRED: "Postal code is required",
  INVALID_POSTALCODE: "Postal code must be 6 digits",
  CITY_REQUIRED: "City is required",
  STATE_REQUIRED: "State is required",
  FAMILY_MEMBER_NAME_REQUIRED: "All family members must have a name",
  IMAGE_FILE_ERROR: "Please select an image file",
  IMAGE_UPLOAD_ERROR: "Failed to upload image",
  PROFILE_UPDATE_SUCCESS: "Profile updated successfully",

  ENTER_POSTAL_CODE: "Enter postal code",

  FULL_NAME: "Full Name",
  ENTER_FULL_NAME: "Enter full name",
  GOTRA: "Gotra",
  GENDER: "Gender",
  MALE: "Male",
  FEMALE: "Female",
  OTHER: "Other",
  MARITAL_STATUS: "Marital Status",
  MARRIED: "Married",
  UNMARRIED: "Unmarried",
  MOBILE_NUMBER: "Mobile Number",
  ENTER_MOBILE_NUMBER: "Enter mobile number",
  EMAIL: "Email",
  ENTER_EMAIL: "Enter email",
  BIRTH_DATE: "Birth Date",
  ENTER_BIRTH_DATE: "Enter birth date",
  PLACE_OF_BIRTH: "Place of Birth",
  ENTER_PLACE_OF_BIRTH: "Enter place of birth",
  TIME_OF_BIRTH: "Time of Birth",
  ANNIVERSARY_DATE: "Anniversary date",
  ENTER_ANNIVERSARY_DATE: "Enter anniversary date",

  GET_IN_TOUCH: "Get in touch",
  CONTACT_DESC: "We'd love to hear from you. Please fill out this form.",
  PHONE_NUMBER: "Phone number",
  ENTER_PHONE_NUMBER: "99999 99999",
  QUERY_TYPE: "Query type",
  SELECT_QUERY_TYPE: "Select a query type",
  PREFERRED_TIME: "Preferred time to contact",
  SELECT_TIME_SLOT: "Select time slot",
  MESSAGE_DETAIL: "Your Message/Query detail",
  ENTER_MESSAGE: "Write....",
  SUBMIT: "Submit",
  SUBMITTING: "Submitting...",
  REPLY_TIME: "*Our team will revert within 24 hours",

  ACTIVE_PAST_PUJA: "Active & Past Puja",
  PRASAD_STATUS: "Prasad Status",
  PRASAD_PACKED: "Your prasad has been packed",
  NO_BOOKINGS_FOUND: "No bookings found!",
  SEARCH_PLACEHOLDER: "Search by name, temple or booking ID",

  BEFORE_RITUAL: "Before you begin the ritual",
  RITUAL_TIP_1: "Bathe and wear clean clothes",
  RITUAL_TIP_2: "Be calm and devoted",
  RITUAL_TIP_3: "Keep the space and mind pure",
  RITUAL_TIP_4: "Follow the priest's guidance",
  MEMBERS_COUNT: "Members",
  ENTER_NAME: "Enter full name",
  SAVE_MEMBERS: "Save",
  MANTRAS: "Mantra Recommended",
  NO_MANTRAS: "No mantra recommended",
  PUJA_STARTED: "Puja Started",
  PUJA_ENDED: "Puja Ended",
  PUJA_COMPLETE: "Puja Complete",
  VIDEO_NOTE:
    "📌 Note: Your complete Seva video will be shared on WhatsApp within 2-3 days after the Chadhava.",
  MAX_LIMIT_REACHED: "The maximum limit has been reached.",
  MEMBERS_UPDATED: "Members updated successfully.",
  ADD: "Add",
  PACKAGE: "Package",
  DATE: "Date",
  TIME: "Time",
  TITHI: "Tithi",
  PRASAD_WILL_DISPATCH_ONCE_PUJA_DONE:
    "Prasad will be dispatched once the puja is done",
  TRACK_YOUR_PRASAD: "Track your Prasad",
  PUJA_WILL_PERFORM_BY: "Puja will be performed by",
  IMP_NOTICE:
    "Important Note: All updates for your Kamakhya Seva, including confirmations and video links, will be shared with you on WhatsApp through our official number: +91 7039858794.",
  PAY_NOW: "Pay now",
  PLZ_FILL_REQ_FIELD:
    "Please enter valid information in the highlighted fields.",
  NOT_AVAILABLE: "Not Available",
  NOT_AVAILABLE_DESC:
    "The information you're looking for is currently unavailable. Please check back later or contact support if you need immediate assistance.",
  NO_MATCHING_RESULT: "No Matching Results",
  NO_MATCHING_RESULT_DESC:
    "We couldn't find any items matching your search criteria. Try different keywords, adjust your filters, or browse our full collection.",
  NOT_LOGGEDIN: "Not Loggedin!",
  NOT_LOGGEDIN_DESC_1: "Please log in to view and manage your cart items.",
  NOT_LOGGEDIN_DESC_2:
    "Already have an account? Sign in or create one to start shopping!",
  LOGIN_HERE: "Login Here",

  LOGIN_TITLE: "Fill your login details",
  MOBILE_TITLE: "Enter your mobile number",
  MOBILE_SUBTITLE:
    "Booking updates, Puja photos, videos & details will be shared on WhatsApp on below number",
  NAME_TITLE: "Enter Your Name",
  NAME_PLACEHOLDER: "Add full name",
  OTP_TITLE: "Enter OTP",
  OTP_SUBTITLE: "We've sent a 6-digit OTP to your mobile number",
  VERIFY: "Verify & Continue",
  RESEND_OTP: "Resend OTP",
  RESEND_TIMER: "Resend OTP",
  LOGIN_SUCCESS: "Login successful",
  OTP_ERROR: "Please enter valid OTP",
  MOBILE_REQUIRED: "Mobile number is required",
  INVALID_MOBILE: "Please enter a valid 10-digit mobile number",
  SHORT_NAME: "Name must be at least 3 characters",
  INVALID_NAME: "Name should contain only letters and spaces",
  OTP_REQUIRED: "OTP is required",
  INVALID_OTP: "OTP must be 6 digits",
  SEARCH_BOOKING: "Search Bookings",
  NO_OFFERINGS_FOUND: "No Offerings Found",
  NO_OFFERINGS_FOUND_DESC:
    "There are currently no offerings available for this puja. Please check back later.",
  ENTER_WHATSAPP_DETAILS: "Enter Whatsapp Number",

  EMPTY_CART_HEAD: "Your Cart is Empty",
  EMPTY_CART_DESC:
    "Looks like you haven't added any items yet. Start shopping to fill your cart!",
  BRW_PROD: "Browse Products",
  DATA_NOT_FOUND: "No Data Found",
  DATA_NOT_FOUND_DESC:
    "We couldn't find any matching results. Try adjusting your search or filters.",
  TRY_NOW: "Try Again",

  PHN_DIGITS_ONLY: "Phone number must contain only digits",
  ABOUT_US: "About Us",
  HOW_GM_STARTED: "How Ghar Mandir started",
  CONTENT_1:
    "Founded by IIM Calcutta, Bain, McKinsey and Bank of America alums",
  CONTENT_2:
    "“Ghar Mandir” is on a mission to revolutionize the way Indians pray!",
  CONTENT_3:
    "With an extensive network of renowned priests and temples, Ghar Mandir offers a seamless experience for booking personalized virtual pujas and a host of other services.",

  CONTENT_4: "Meet the Co-Founders",
  CONTENT_5: "Know more about the people behind Ghar Mandir",

  DIVINE_JOURNEY_HEADING: "Our Divine Journey in Numbers",
  PUJA_CHADHAWA_OFFERED: "Puja and Chadhava offered",
  PUJA_CHADHAWA_COUNT: "6,00,000+",
  PUJA_CHADHAWA_DESC:
    "For years, we've delivered pujas and chadhawas with faith and sincerity trusted by thousands.",
  TRUSTED_USERS: "Trusted Users",
  TRUSTED_USERS_COUNT: "2,00,000+",
  TRUSTED_USERS_DESC:
    "Serving pujas and chadhawas for years, delivering blessings and tradition to your doorstep.",
  ASSOCIATED_TEMPLES: "Associated number of Temples",
  ASSOCIATED_TEMPLES_COUNT: "50+",
  ASSOCIATED_TEMPLES_DESC:
    "Bringing you pujas and chadhawas from trusted temples, delivered with devotion for years.",
  ROOTED_IN_HINDUISM: "Rooted in Hinduism",
  WHO_WE_ARE_HEADING: "Who We Are",
  WHO_WE_ARE_DESC:
    "We are a team devoted to preserving and sharing the essence of Hindu culture through sacred rituals, offerings, and meaningful practices. Rooted in tradition, driven by devotion.",
  OUR_PHILOSOPHY_HEADING: "Our Philosophy",
  OUR_PHILOSOPHY_DESC:
    "We believe that spirituality is a way of life guided by dharma, shaped by karma, and nurtured through daily acts of devotion. Each puja, each chadhawa, is a step closer to inner peace and divine connection.",
  CULTURE_WE_CHERISH_HEADING: "Culture We Cherish",
  CULTURE_WE_CHERISH_DESC:
    "From ancient temples to everyday homes, Hinduism lives through its rituals, festivals, and values. We aim to make these timeless traditions accessible and relevant in today's world.",
  DEVOTEES_THOUGHTS_HEADING: "Devotees Thoughts",
  DEVOTEE_1_COMMENT:
    "Main to Dhanya ho gai Hanuman Giri ka Prasad pakar Bajrangbali ki kripa aap logon Ko sada banaa Rahe aur aap logon ke dwara mujhmein per banaa Rahe bhakti- bhut dhanyvad 🙏🙏",
  DEVOTEE_1_NAME: "-Ruby Singh",
  DEVOTEE_2_COMMENT:
    "Jai Badri Vishal . Mai bahot bhagyshalali hu ki Ghar Mandir dwara Ayojit Badhidham Tulsi Chadhava Pooja ka Vidio Prapat huva Badri Pandittone Bahot acchi tarah Pooja karawaya hai. Muze khushi hai maine Pooja Chadhava mai bhag liya ,participat kiya Dhanyawad Ghar Mandir. Thanks a Lot",
  DEVOTEE_2_NAME: "-Sanjay Bajrang Channe",
  DEVOTEE_3_COMMENT:
    "Aap ki team ek bohot acha kaam kar rahi h .... Jo log door tirth nhi kar pate wo ghar bethe hi pooja karwa kar laabh uthate h .... aapka sab ka bohot bohot dhanyawad 🙏",
  DEVOTEE_3_NAME: "-Rajeev Nohwal",
  WE_ARE_LOOKING_HEADING: "We are looking for fellow builders",
  WE_ARE_LOOKING_SUBHEADING:
    "If you're driven to make an impact in India's fast-growing devotion-tech space, reach out:",
  HIRING_EMAIL: "recruit@gharmandir.in",
};
// export const HINDI_LANG: Record<string, string> = {
//   WELCOME: "स्वागत है",
//   WHY_BOOK_US_HEAD: "हमसे बुकिंग क्यों करें",
//   WHY_BOOK_US_DESC: "हम आपकी चुनौतियों में मार्गदर्शन करने के लिए यहाँ हैं",
//   WHY_BOOK_US_HEAD_1: "2 लाख+ भक्तों की सेवा की गई",
//   WHY_BOOK_US_DESC_1:
//     "प्रमाणित पुजारियों द्वारा प्रामाणिक वैदिक विधि से अनुष्ठान",
//   WHY_BOOK_US_HEAD_2: "विश्वसनीय मंदिर",
//   WHY_BOOK_US_DESC_2:
//     "क्षेत्र के प्रसिद्ध और विश्वसनीय मंदिरों में सेवाएँ बुक करें।",
//   WHY_BOOK_US_HEAD_3: "प्रसाद डिलीवरी",
//   WHY_BOOK_US_DESC_3: "हर बुकिंग के बाद आपके घर तक प्रसाद पहुँचाया जाएगा।",
//   WHY_BOOK_US_HEAD_4: "आसान बुकिंग",
//   WHY_BOOK_US_DESC_4:
//     "आपकी सभी आध्यात्मिक आवश्यकताओं के लिए सरल और परेशानी मुक्त बुकिंग प्रक्रिया।",
//   UPCOMING_PUJA_HEAD: "आगामी पूजा",
//   UPCOMING_PUJA_SUBHEAD:
//     "विश्वसनीय मंदिरों से पवित्र पूजा का अनुभव करें—व्यक्तिगत अनुष्ठान, वीडियो प्रमाण और आपके घर तक प्रसाद।",
//   UPCOMING_PUJA_DESC:
//     "आशीर्वाद और सकारात्मक ऊर्जा प्राप्त करने के लिए एक आध्यात्मिक अनुष्ठान",
//   EXPLORE_MORE_PUJA: "और पूजा देखें",
//   EXPLORE_MORE_CHADHAVA: "और चढ़ावा देखें",
//   VIEW_ALL: "सभी देखें",
//   UPCOMING_CHADHAVA_HEAD: "आगामी चढ़ावा",
//   UPCOMING_CHADHAVA_SUBHEAD:
//     "विश्वसनीय मंदिरों से पवित्र पूजा का अनुभव करें—व्यक्तिगत अनुष्ठान, वीडियो प्रमाण और आपके घर तक प्रसाद।",
//   UPCOMING_CHADHAVA_DESC:
//     "आशीर्वाद और शांति प्राप्त करने के लिए एक भक्ति चढ़ावा",
//   HOW_WORK_HEAD: "यह कैसे काम करता है?",
//   HOW_WORK_HEAD_1: "चढ़ावा",
//   HOW_WORK_DESC_1: "अपना आशीर्वाद पैकेज चुनें और चढ़ावा विकल्प चुनें",
//   HOW_WORK_HEAD_2: "विवरण",
//   HOW_WORK_DESC_2: "नाम और गोत्र भरें और दक्षिणा दें",
//   HOW_WORK_HEAD_3: "विधि",
//   HOW_WORK_DESC_3: "पंडित जी निर्धारित तिथि पर चढ़ावा अर्पित करेंगे",
//   HOW_WORK_HEAD_4: "आशीर्वाद",
//   HOW_WORK_DESC_4: "2-3 दिनों में व्हाट्सएप पर वीडियो प्राप्त करें",
//   FAQ_HEAD: "अक्सर पूछे जाने वाले प्रश्न (FAQ)",
//   FAQ_QUES_1: "इस पूजा में क्या किया जाएगा?",
//   FAQ_ANS_1: `हमारे पंडित जी, जो प्रसिद्ध मंदिरों में पूजा कराते हैं, वैदिक अनुष्ठानों में अत्यधिक ज्ञान और अनुभव रखते हैं। हर पूजा घर मंदिर के माध्यम से हमेशा आपके नाम और गोत्र में की जाती है, जैसा कि हमारे वेदों में उल्लेखित है। हमारे पंडित जी आपकी पूजा प्राचीन शास्त्रों में बताए गए सही मंत्रों और विधियों से करेंगे। पूजा पूर्ण होने के बाद, पंडित जी आपके परिवार की भलाई और आपकी सफलता के लिए प्रार्थना करेंगे।`,
//   FAQ_QUES_2: "मुझे कैसे पता चलेगा कि पूजा हो गई है?",
//   FAQ_ANS_2: `घर मंदिर एक विश्वसनीय भक्ति ब्रांड है जहाँ हम हर पूजा सनातन धर्म के अनुसार करते हैं। मंदिर के हमारे अनुभवी पंडित आपके नाम और गोत्र में वैदिक अनुष्ठान सावधानीपूर्वक करेंगे और आपकी खुशी और सफलता के लिए प्रार्थना करेंगे। अनुष्ठान पूर्ण होने के बाद, हम आपकी पूजा का व्यक्तिगत वीडियो आपके व्हाट्सएप नंबर पर साझा करेंगे। साथ ही, पूजा का प्रसाद (यदि चुना गया हो) आपके घर तक पहुँचाया जाएगा।`,
//   FAQ_QUES_3: "मुझे अपना गोत्र नहीं पता, क्या करूँ?",
//   FAQ_ANS_3: `हम सबसे पहले आपको सलाह देंगे कि आप अपने परिवार के बुजुर्गों से अपने गोत्र की जानकारी प्राप्त करने का प्रयास करें। यदि आपके परिवार में कोई भी गोत्र की जानकारी नहीं जानता है, तो आप शास्त्रों के मार्गदर्शन का पालन कर सकते हैं। शास्त्रों के अनुसार, यदि किसी को अपना गोत्र नहीं पता है तो वे कश्यप गोत्र मान सकते हैं। अतः आप बुकिंग करते समय संकल्प फॉर्म में कश्यप गोत्र लिख सकते हैं और अपनी बुकिंग पूरी कर सकते हैं।`,
//   BLESSED_MOMENTS_VIDEO_HEAD: "भक्तों के धन्य क्षण",
//   DIVINE_EXPERIENCE: "पिछले पूजा वीडियो",
//   DEVOTEE_REVIEWS: "भक्तों के विचार",
//   JOIN_OUR_DIVINE_COMMUNITY: "हमारे दिव्य समुदाय से जुड़ें",
//   SPIRITUAL_BANNER_HEAD: "किस पूजा का चयन करें, इसे लेकर उलझन में हैं?",
//   SPIRITUAL_BANNER_SUBHEAD_1: "सही अनुष्ठान खोजने के लिए मार्गदर्शन चाहिए?",
//   SPIRITUAL_BANNER_SUBHEAD_2:
//     "हम आपकी सही आध्यात्मिक पसंद में मदद करने के लिए यहाँ हैं।",
//   SPIRITUAL_BANNER_BTN: "आध्यात्मिक सहायता प्राप्त करें",
//   SELECT_PACKAGE: "पैकेज चुनें",
//   WHY_PERFORM_THIS_PUJA: "यह पूजा क्यों करें?",
//   ABOUT_TEMPLE: "मंदिर के बारे में",
//   PUJA_PERFORM_BY: "पूजा संपन्नकर्ता ",
//   PUJA_NO_LONGER_AVAILABLE: "पूजा अब उपलब्ध नहीं है",
//   UNAVAILABLE: "उपलब्ध नहीं",
//   PACKAGE_PRICE: "पैकेज मूल्य",
//   CHOOSE_YOUR_PACKAGE: "अपना पैकेज चुनें",
//   WHAT_WILL_YOU_GET: "आपको क्या मिलेगा",
//   WHY_PERFORM_HEAD_1:"आपके नाम पर मंदिर में चढ़ावा" ,
//   WHY_PERFORM_DESC_1:
//     "आपकी पूजा आपके नाम और गोत्र में संपन्न की जाएगी, जिससे एक वास्तव में व्यक्तिगत अनुष्ठान सुनिश्चित होगा। हमारे पंडित वैदिक परंपराओं का पालन करते हुए विशेष रूप से आपके और आपके परिवार के लिए आशीर्वाद प्राप्त करते हैं।",
//   WHY_PERFORM_HEAD_2: "व्हाट्सएप पर अपना पूजा वीडियो प्राप्त करें",
//   WHY_PERFORM_HEAD_3: "प्रसाद आपके द्वार पर पहुँचाया जाएगा",
//   ADD_PRASAD: "प्रसाद जोड़ें",
//   ADD_CHADHAVA_IN_THALI: "थाली में चढ़ावा जोड़ें",
//   CHADHAVA_NO_LONGER_AVAILABLE: "चढ़ावा अब उपलब्ध नहीं है",
//   ADD_TO_YOUR_THALI: "अपनी थाली में जोड़ें",
//   CHOOSE_YOUR_CHADHAVA: "अपना चढ़ावा चुनें",
//   ADD_CHADHAVA: "चढ़ावा जोड़ें",
//   ADD_OFFERINGS: "आहुतियाँ जोड़ें",
//   ADD_PLUS: "जोड़ें+",
//   ONWARDS: "से शुरू",
//   OUT_OF_STOCK: "उपलब्ध नहीं",
//   CHADHAVA_SELECTED: "चयनित चढ़ावा",
//   ADD_MORE_OFFERINGS: "और आहुतियाँ जोड़ें",
//   TOTAL: "कुल",
//   ADD_YOUR_SANKALP: "अपना संकल्प जोड़ें",
//   PACKAGE_OFFERINGS: "पैकेज में आहुतियाँ",
//   CHECKOUT: "चेकआउट",
//   TOTAL_PRICE: "कुल कीमत",
//   EDIT_PACKAGE: "पैकेज चुनें",
//   PUJA_SELECTED: "चयनित पूजा",
//   SELECTED: "चयनित",
//   PRASAD: "प्रसाद",
//   AD_ONS: "चढ़ावा",
//   OFFERING_PRASAD_ERROR: "कृपया कम से कम एक आहुति या प्रसाद चुनें",
//   PLZ_SELECT_PACKAGE: "कृपया एक पैकेज चुनें",
//   YOUR_PUJA: "आपकी पूजा",
//   YOUR_CHADHAVA: "आपका चढ़ावा",
//   ARE_YOU_SURE_WANT_TO_REMOVE: "क्या आप वाकई इसे हटाना चाहते हैं?",
//   REMOVED_SUCCESSFULLY: "सफलतापूर्वक हटाया गया",
//   REMOVE: "हटाएँ",
//   EDIT: "बदलें",
//   NO_PACKAGE: "कोई पैकेज नहीं",
//   ENTER_CONTACT_DETAILS: "संपर्क विवरण दर्ज करें",
//   ENTER_YOUR_NAME: "अपना नाम दर्ज करें",
//   WILL_BE_USED_FOR_SENDING_VIDEO_OF_SEVA:
//     "सेवा का वीडियो भेजने के लिए उपयोग किया जाएगा",
//   WILL_BE_RICTED_DURING_SEVA: "सेवा के दौरान उच्चारित किया जाएगा",
//   ADD_FAMILY_MEMBER: "परिवार के सदस्य जोड़ें",
//   MEMBER_PARTICIPATING: "सहभागी सदस्य",
//   SEVA_PERFORM_BY_THIS_NAME: "सेवा इस नाम से संपन्न की जाएगी",
//   ADD_MEMBER_WITH_50_RUPEE: `प्रत्येक अतिरिक्त सदस्य के लिए ${getSign()}${
//     currency_name == "INR" ? "50" : "5"
//   } का शुल्क लगेगा`,
//   ENTER_FAMILY_MEMBER_NAME: "परिवार के सदस्य का नाम दर्ज करें",
//   ADD_MEMBER: "+ सदस्य जोड़ें",
//   GOTRA_OF_MEBMBER: "सदस्य का गोत्र",
//   ENTER_GOTRA: "गोत्र दर्ज करें",
//   NOT_KNOW_GOTRA: "मुझे अपना गोत्र नहीं पता",
//   ADDRESS: "पता",
//   ADDRESS_DESC: "प्रसाद इसी पते पर भेजा जाएगा",
//   STREET_ADDRESS: "मुख्य पता",
//   HOUSE_NUMBER_STREET_NAME: "मकान नंबर और गली/मोहल्ला का नाम",
//   POSTAL_CODE: "पिन कोड",
//   TOWN_CITY: "शहर/कस्बा",
//   ENTER_CITY: "शहर दर्ज करें",
//   STATE_REGION: "राज्य/प्रदेश",
//   ENTER_STATE: "राज्य दर्ज करें",
//   MEMBER_SHDNT_EMPTY: "सदस्य का नाम खाली नहीं होना चाहिए",
//   MEMBER_SHDNT_EMPTY_EXCEED_20_CHAR:
//     "सदस्य का नाम 20 अक्षरों से अधिक नहीं होना चाहिए",
//   NAME_SHDNT_EMPTY: "नाम का फील्ड खाली नहीं होना चाहिए",
//   POSTAL_CODE_ERROR: "पिन कोड 6 अंकों का होना चाहिए",
//   SHDNT_EXCEED_20_CHAR: "80 अक्षरों से अधिक नहीं होना चाहिए",
//   IS_REQUIRED: "आवश्यक है",
//   PHN_REQ: "फोन नंबर आवश्यक है",
//   PHN_REQ_WARN: "फोन नंबर 10 अंकों का होना चाहिए",
//   "Street address": "सड़क का पता",
//   "Postal code": "पिन कोड",
//   "Town/City": "शहर/कस्बा",
//   City: "शहर",
//   "State/Region": "राज्य/प्रदेश",
//   State: "राज्य",
//   CITY_NOT_FOUND: "इस पिनकोड के लिए शहर नहीं मिला",
//   RECOMMENDED_CHADHAVA: "सुझाया गया चढ़ावा",
//   ALREADY_IN_CART: "पहले से जोड़ा हुआ। आप इसे कार्ट में बदल या हटा सकते हैं",
//   ADDED: "जोड़ा गया",
//   HOME: "होम", // or "मुखपृष्ठ" for more formal Hindi
//   PUJA: "पूजा",
//   CHADHAVA: "चढ़ावा",
//   CONTACT_US: "हमसे संपर्क करें",
//   SLOGAN: "आपकी श्रद्धा, हमारी ज़िम्मेदारी",
//   QUICK_LINKS: "त्वरित लिंक्स",
//   PARTICIPATE_NOW: "अभी भाग लें",
//   NEED_ASSISTANCE: "क्या आपके जीवन की समस्याओं के लिए सहायता चाहिए?",
//   GET_ASSISTANCE: "सहायता प्राप्त करें",
//   COMPLETE_PROFILE: "प्रोफ़ाइल पूरी करें",
//   COMPLETE_PROFILE_FOR_EXP:
//     "एक सुगम आध्यात्मिक अनुभव के लिए अपनी प्रोफ़ाइल पूरी करें",
//   BOOKINGS: "बुकिंग्स",
//   PROFILE: "प्रोफ़ाइल",
//   LOG_OUT: "लॉग आउट",
//   PROFILE_TITLE: "प्रोफ़ाइल",
//   PROFILE_PICTURE: "प्रोफ़ाइल चित्र",
//   PERSONAL_DETAILS: "व्यक्तिगत विवरण",
//   FAMILY_MEMBERS: "परिवार के सदस्य",
//   SAVE_CHANGES: "परिवर्तन सहेजें",
//   CHANGE_PICTURE: "बदलें",
//   NAME_REQUIRED: "पूरा नाम आवश्यक है",
//   EMAIL_REQUIRED: "ईमेल आवश्यक है",
//   INVALID_EMAIL: "ईमेल प्रारूप अमान्य है",
//   PHONE_REQUIRED: "फोन नंबर आवश्यक है",
//   INVALID_PHONE: "फोन नंबर प्रारूप अमान्य है",
//   BIRTHDATE_REQUIRED: "जन्म तिथि आवश्यक है",
//   GENDER_REQUIRED: "लिंग आवश्यक है",
//   BIRTHPLACE_REQUIRED: "जन्म स्थान आवश्यक है",
//   BIRTHTIME_REQUIRED: "जन्म समय आवश्यक है",
//   STREET_REQUIRED: "मुख्य पता आवश्यक है",
//   POSTALCODE_REQUIRED: "पिन कोड आवश्यक है",
//   INVALID_POSTALCODE: "पिन कोड 6 अंकों का होना चाहिए",
//   CITY_REQUIRED: "शहर आवश्यक है",
//   STATE_REQUIRED: "राज्य आवश्यक है",
//   FAMILY_MEMBER_NAME_REQUIRED: "सभी परिवार के सदस्यों का नाम आवश्यक है",
//   IMAGE_FILE_ERROR: "कृपया एक छवि फ़ाइल चुनें",
//   IMAGE_UPLOAD_ERROR: "छवि अपलोड करने में विफल",
//   PROFILE_UPDATE_SUCCESS: "प्रोफ़ाइल सफलतापूर्वक अपडेट की गई",
//   ENTER_POSTAL_CODE: "पिन कोड दर्ज करें",
//   FULL_NAME: "पूरा नाम",
//   ENTER_FULL_NAME: "पूरा नाम दर्ज करें",
//   GOTRA: "गोत्र",
//   GENDER: "लिंग",
//   MALE: "पुरुष",
//   FEMALE: "महिला",
//   OTHER: "अन्य",
//   MARITAL_STATUS: "वैवाहिक स्थिति",
//   MARRIED: "विवाहित",
//   UNMARRIED: "अविवाहित",
//   MOBILE_NUMBER: "मोबाइल नंबर",
//   ENTER_MOBILE_NUMBER: "मोबाइल नंबर दर्ज करें",
//   EMAIL: "ईमेल",
//   ENTER_EMAIL: "ईमेल दर्ज करें",
//   BIRTH_DATE: "जन्म तिथि",
//   ENTER_BIRTH_DATE: "जन्म तिथि दर्ज करें",
//   PLACE_OF_BIRTH: "जन्म स्थान",
//   ENTER_PLACE_OF_BIRTH: "जन्म स्थान दर्ज करें",
//   TIME_OF_BIRTH: "जन्म का समय",
//   ANNIVERSARY_DATE: "विवाह की वर्षगांठ",
//   ENTER_ANNIVERSARY_DATE: "विवाह की वर्षगांठ दर्ज करें",
//   ADD: "जोड़ें",
//   GET_IN_TOUCH: "संपर्क में आएं",
//   CONTACT_DESC: "हम आपसे सुनना पसंद करेंगे। कृपया यह फ़ॉर्म भरें।",
//   PHONE_NUMBER: "फ़ोन नंबर",
//   ENTER_PHONE_NUMBER: "99999 99999",
//   QUERY_TYPE: "प्रश्न प्रकार",
//   SELECT_QUERY_TYPE: "प्रश्न प्रकार चुनें",
//   PREFERRED_TIME: "संपर्क का पसंदीदा समय",
//   SELECT_TIME_SLOT: "समय स्लॉट चुनें",
//   MESSAGE_DETAIL: "आपका संदेश/प्रश्न विवरण",
//   ENTER_MESSAGE: "लिखें....",
//   SUBMIT: "सबमिट करें",
//   SUBMITTING: "सबमिट किया जा रहा है...",
//   REPLY_TIME: "*हमारी टीम 24 घंटे के भीतर उत्तर देगी",

//   ACTIVE_PAST_PUJA: "सक्रिय और पिछली पूजा",
//   PRASAD_STATUS: "प्रसाद की स्थिति",
//   PRASAD_PACKED: "आपका प्रसाद पैक किया गया है",
//   NO_BOOKINGS_FOUND: "कोई बुकिंग नहीं मिली!",
//   SEARCH_PLACEHOLDER: "नाम, मंदिर या बुकिंग ID से खोजें",

//   BEFORE_RITUAL: "पूजा शुरू करने से पहले",
//   RITUAL_TIP_1: "स्नान करें और स्वच्छ वस्त्र धारण करें",
//   RITUAL_TIP_2: "शांत और भक्तिभाव रहें",
//   RITUAL_TIP_3: "स्थान और मन को शुद्ध रखें",
//   RITUAL_TIP_4: "पुजारी के मार्गदर्शन का पालन करें",
//   MEMBERS_COUNT: "सदस्य",
//   ENTER_NAME: "पूरा नाम दर्ज करें",
//   SAVE_MEMBERS: "सहेजें",
//   MANTRAS: "मंत्र सुझाव",
//   NO_MANTRAS: "कोई मंत्र सुझाव नहीं",
//   PUJA_STARTED: "पूजा शुरू",
//   PUJA_ENDED: "पूजा समाप्त",
//   PUJA_COMPLETE: "पूजा पूर्ण",
//   VIDEO_NOTE:
//     "📌 नोट: चढ़ावा के 2-3 दिनों के भीतर आपका पूर्ण सेवा वीडियो व्हाट्सएप पर साझा किया जाएगा।",
//   MAX_LIMIT_REACHED: "अधिकतम सीमा पहुँच गई है।",
//   MEMBERS_UPDATED: "सदस्य सफलतापूर्वक अपडेट किए गए।",
//   PACKAGE: "पैकेज",
//   DATE: "तारीख",
//   TIME: "समय",
//   TITHI: "तिथि",
//   PRASAD_WILL_DISPATCH_ONCE_PUJA_DONE:
//     "पूजा पूरी होने के बाद प्रसाद भेजा जाएगा",
//   TRACK_YOUR_PRASAD: "अपने प्रसाद को ट्रैक करें",
//   PUJA_WILL_PERFORM_BY: "पूजा द्वारा संपन्न कराई जाएगी",
//   IMP_NOTICE:
//     "महत्वपूर्ण सूचना: आपके कामाख्या सेवा से जुड़े सभी अपडेट, जिसमें पुष्टिकरण और वीडियो लिंक शामिल हैं, आपके व्हाट्सएप पर हमारे आधिकारिक नंबर +91 7039858794 के माध्यम से साझा किए जाएंगे।",
//   PAY_NOW: "अभी भुगतान करें",
//   PLZ_FILL_REQ_FIELD:
//     "कृपया हाइलाइट किए गए फ़ील्ड्स में सही जानकारी दर्ज करें।", //"कृपया सभी आवश्यक फ़ील्ड भरें",
//   NOT_AVAILABLE: "उपलब्ध नहीं",
//   NOT_AVAILABLE_DESC:
//     "आपके द्वारा खोजी जा रही जानकारी वर्तमान में उपलब्ध नहीं है। कृपया बाद में पुनः जांचें या यदि आपको तत्काल सहायता चाहिए तो समर्थन टीम से संपर्क करें।",
//   NO_MATCHING_RESULT: "कोई मिलते-जुलते परिणाम नहीं",
//   NO_MATCHING_RESULT_DESC:
//     "हमें आपकी खोज शर्तों से मेल खाता कोई आइटम नहीं मिला। कृपया अलग कीवर्ड आज़माएँ, अपने फ़िल्टर्स को समायोजित करें, या हमारे संपूर्ण संग्रह को ब्राउज़ करें।",
//   NOT_LOGGEDIN: "लॉगिन नहीं किया!",
//   NOT_LOGGEDIN_DESC_1:
//     "अपने कार्ट आइटम्स को देखने और प्रबंधित करने के लिए कृपया लॉग इन करें।",
//   NOT_LOGGEDIN_DESC_2:
//     "पहले से ही एक खाता है? शॉपिंग शुरू करने के लिए साइन इन करें या नया खाता बनाएँ!",
//   LOGIN_HERE: "यहाँ लॉगिन करें",
//   LOGIN_TITLE: "अपना लॉगिन विवरण भरें",
//   MOBILE_TITLE: "अपना मोबाइल नंबर दर्ज करें",
//   MOBILE_SUBTITLE:
//     "बुकिंग अपडेट, पूजा फोटो, वीडियो और विवरण नीचे दिए गए नंबर पर व्हाट्सएप पर साझा किए जाएंगे",
//   NAME_TITLE: "अपना नाम दर्ज करें",
//   NAME_PLACEHOLDER: "पूरा नाम जोड़ें",
//   OTP_TITLE: "OTP दर्ज करें",
//   OTP_SUBTITLE: "हमने आपके मोबाइल नंबर पर 6-अंकीय OTP भेजा है",
//   VERIFY: "सत्यापित करें और जारी रखें",
//   RESEND_OTP: "OTP पुनः भेजें",
//   RESEND_TIMER: "OTP पुनः भेजें",
//   LOGIN_SUCCESS: "लॉगिन सफल",
//   OTP_ERROR: "कृपया वैध OTP दर्ज करें",
//   MOBILE_REQUIRED: "मोबाइल नंबर आवश्यक है",
//   INVALID_MOBILE: "कृपया 10 अंकों का वैध मोबाइल नंबर दर्ज करें",
//   SHORT_NAME: "नाम कम से कम 3 वर्णों का होना चाहिए",
//   INVALID_NAME: "नाम में केवल अक्षर और रिक्त स्थान होने चाहिए",
//   OTP_REQUIRED: "OTP आवश्यक है",
//   INVALID_OTP: "OTP 6 अंकों का होना चाहिए",
//   SEARCH_BOOKING: "बुकिंग्स खोजें",
//   NO_OFFERINGS_FOUND: "कोई चढ़ावा उपलब्ध नहीं",
//   NO_OFFERINGS_FOUND_DESC:
//     "इस पूजा के लिए वर्तमान में कोई चढ़ावा उपलब्ध नहीं है। कृपया बाद में पुनः जांचें।",
//   ENTER_WHATSAPP_DETAILS: "व्हाट्सएप नंबर दर्ज करें",

//   EMPTY_CART_HEAD: "आपका कार्ट खाली है",
//   EMPTY_CART_DESC:
//     "लगता है आपने अभी तक कोई आइटम नहीं जोड़ा है। अपना कार्ट भरने के लिए खरीदारी शुरू करें!",
//   BRW_PROD: "उत्पाद देखें",
//   DATA_NOT_FOUND: "कोई डेटा नहीं मिला",
//   DATA_NOT_FOUND_DESC:
//     "हमें कोई मिलान करने वाले परिणाम नहीं मिले। कृपया अपनी खोज या फिल्टर समायोजित करके पुनः प्रयास करें।",
//   TRY_NOW: "पुनः प्रयास करें",
//   ABOUT_US: "हमारे बारे में",
//   HOW_GM_STARTED: "घर मंदिर की शुरुआत कैसे हुई?",
//   CONTENT_1:
//     "आईआईएम कलकत्ता, बैन, मैकिन्से और बैंक ऑफ अमेरिका के पूर्व छात्रों द्वारा स्थापित",
//   CONTENT_2:
//     "“घर मंदिर” भारतीयों की प्रार्थना करने के तरीके में क्रांतिकारी बदलाव लाने के मिशन पर है!",
//   CONTENT_3:
//     "प्रसिद्ध पुजारियों और मंदिरों के व्यापक नेटवर्क के साथ, घर मंदिर व्यक्तिगत वर्चुअल पूजा और कई अन्य सेवाओं की बुकिंग के लिए एक सहज अनुभव प्रदान करता है।",
//   CONTENT_4: "संस्थापकों से मिलिए",
//   CONTENT_5: "घर मंदिर के पीछे के लोगों के बारे में जानें",

//   DIVINE_JOURNEY_HEADING: "हमारी दिव्य यात्रा संख्याओं में",
//   PUJA_CHADHAWA_OFFERED: "पूजा और चढ़ावा अर्पित",
//   PUJA_CHADHAWA_COUNT: "6,00,000+",
//   PUJA_CHADHAWA_DESC:
//     "वर्षों से, हम हजारों लोगों के विश्वास और ईमानदारी से पूजा और चढ़ावा पहुंचा रहे हैं।",
//   TRUSTED_USERS: "विश्वसनीय उपयोगकर्ता",
//   TRUSTED_USERS_COUNT: "2,00,000+",
//   TRUSTED_USERS_DESC:
//     "वर्षों से पूजा और चढ़ावा की सेवा करते हुए, आपके द्वार तक आशीर्वाद और परंपरा पहुंचाना।",
//   ASSOCIATED_TEMPLES: "संबद्ध मंदिरों की संख्या",
//   ASSOCIATED_TEMPLES_COUNT: "50+",
//   ASSOCIATED_TEMPLES_DESC:
//     "विश्वसनीय मंदिरों से पूजा और चढ़ावा लाकर, वर्षों से भक्ति के साथ आप तक पहुंचाना।",

//   ROOTED_IN_HINDUISM: "हिंदू धर्म में निहित",
//   WHO_WE_ARE_HEADING: "हम कौन हैं",
//   WHO_WE_ARE_DESC:
//     "हम एक ऐसी टीम हैं जो हिंदू संस्कृति के सार को पवित्र अनुष्ठानों, भेंटों और सार्थक प्रथाओं के माध्यम से संरक्षित और साझा करने के लिए समर्पित है। परंपरा में निहित, भक्ति से प्रेरित।",
//   OUR_PHILOSOPHY_HEADING: "हमारा दर्शन",
//   OUR_PHILOSOPHY_DESC:
//     "हम मानते हैं कि आध्यात्मिकता धर्म द्वारा निर्देशित, कर्म द्वारा आकारित और भक्ति के दैनिक कर्मों द्वारा पोषित जीवन का एक तरीका है। प्रत्येक पूजा, प्रत्येक चढ़ावा, आंतरिक शांति और दिव्य संबंध की ओर एक कदम है।",
//   CULTURE_WE_CHERISH_HEADING: "हमारी संस्कृति जिसे हम संजोते हैं",
//   CULTURE_WE_CHERISH_DESC:
//     "प्राचीन मंदिरों से लेकर रोजमर्रा के घरों तक, हिंदू धर्म अपने अनुष्ठानों, त्योहारों और मूल्यों के माध्यम से जीवित है। हम इन कालातीत परंपराओं को आज की दुनिया में सुलभ और प्रासंगिक बनाना चाहते हैं।",

//   DEVOTEES_THOUGHTS_HEADING: "भक्तों के विचार",
//   DEVOTEE_1_COMMENT:
//     "मैं तो धन्य हो गई हनुमान गिरी का प्रसाद पाकर बजरंगबली की कृपा आप लोगों को सदा बनाए रहे और आप लोगों के द्वारा मुझमें भक्ति की प्रेरणा बनाए रखने के लिए बहुत धन्यवाद 🙏🙏",
//   DEVOTEE_1_NAME: "-रूबी सिंह",
//   DEVOTEE_2_COMMENT:
//     "जय बद्री विशाल। मैं बहुत भाग्यशाली हूं कि घर मंदिर द्वारा आयोजित बद्रीधाम तुलसी चढ़ावा पूजा का वीडियो प्राप्त हुआ। बद्री पंडितों ने बहुत अच्छी तरह से पूजा करवाई है। मुझे खुशी है कि मैंने इस पूजा चढ़ावा में भाग लिया। धन्यवाद घर मंदिर। थैंक्स अ लॉट",
//   DEVOTEE_2_NAME: "-संजय बजरंग चाने",
//   DEVOTEE_3_COMMENT:
//     "आपकी टीम बहुत अच्छा काम कर रही है.... जो लोग दूर तीर्थ नहीं जा पाते वे घर बैठे ही पूजा करवाकर लाभ उठा रहे हैं.... आपका बहुत बहुत धन्यवाद 🙏",
//   DEVOTEE_3_NAME: "-राजीव नोहवाल",

//   WE_ARE_LOOKING_HEADING: "हम साथी निर्माताओं की तलाश में हैं",
//   WE_ARE_LOOKING_SUBHEADING:
//     "यदि आप भारत के तेजी से बढ़ते डिवोशन-टेक क्षेत्र में प्रभाव बनाने के लिए प्रेरित हैं, तो संपर्क करें:",
//   HIRING_EMAIL: "recruit@gharmandir.in",
// };
