export const countryCodes = [
  { code: "+93", name: "Afghanistan", iso: "af", minlen: 10, maxlen: 11 },
  { code: "+355", name: "Albania", iso: "al", minlen: 11, maxlen: 12 },
  { code: "+213", name: "Algeria", iso: "dz", minlen: 10, maxlen: 11 },
  { code: "+376", name: "Andorra", iso: "ad", minlen: 9, maxlen: 10 },
  { code: "+244", name: "Angola", iso: "ao", minlen: 10, maxlen: 11 },
  { code: "+54", name: "Argentina", iso: "ar", minlen: 11, maxlen: 13 },
  { code: "+374", name: "Armenia", iso: "am", minlen: 10, maxlen: 11 },
  { code: "+61", name: "Australia", iso: "au", minlen: 10, maxlen: 11 },
  { code: "+43", name: "Austria", iso: "at", minlen: 10, maxlen: 13 },
  { code: "+994", name: "Azerbaijan", iso: "az", minlen: 10, maxlen: 12 },
  { code: "+1-242", name: "Bahamas", iso: "bs", minlen: 11, maxlen: 11 },
  { code: "+973", name: "Bahrain", iso: "bh", minlen: 10, maxlen: 11 },
  { code: "+880", name: "Bangladesh", iso: "bd", minlen: 11, maxlen: 13 },
  { code: "+1-246", name: "Barbados", iso: "bb", minlen: 11, maxlen: 11 },
  { code: "+375", name: "Belarus", iso: "by", minlen: 11, maxlen: 12 },
  { code: "+32", name: "Belgium", iso: "be", minlen: 10, maxlen: 11 },
  { code: "+501", name: "Belize", iso: "bz", minlen: 10, maxlen: 10 },
  { code: "+229", name: "Benin", iso: "bj", minlen: 10, maxlen: 11 },
  { code: "+975", name: "Bhutan", iso: "bt", minlen: 9, maxlen: 10 },
  { code: "+591", name: "Bolivia", iso: "bo", minlen: 10, maxlen: 11 },
  { code: "+387", name: "Bosnia and Herzegovina", iso: "ba", minlen: 10, maxlen: 11 },
  { code: "+267", name: "Botswana", iso: "bw", minlen: 10, maxlen: 11 },
  { code: "+55", name: "Brazil", iso: "br", minlen: 11, maxlen: 13 },
  { code: "+359", name: "Bulgaria", iso: "bg", minlen: 10, maxlen: 12 },
  { code: "+226", name: "Burkina Faso", iso: "bf", minlen: 10, maxlen: 11 },
  { code: "+257", name: "Burundi", iso: "bi", minlen: 10, maxlen: 11 },
  { code: "+855", name: "Cambodia", iso: "kh", minlen: 10, maxlen: 11 },
  { code: "+237", name: "Cameroon", iso: "cm", minlen: 10, maxlen: 11 },
  { code: "+1", name: "Canada", iso: "ca", minlen: 11, maxlen: 11 },
  { code: "+235", name: "Chad", iso: "td", minlen: 10, maxlen: 11 },
  { code: "+56", name: "Chile", iso: "cl", minlen: 11, maxlen: 12 },
  { code: "+86", name: "China", iso: "cn", minlen: 11, maxlen: 13 },
  { code: "+57", name: "Colombia", iso: "co", minlen: 11, maxlen: 12 },
  { code: "+506", name: "Costa Rica", iso: "cr", minlen: 10, maxlen: 11 },
  { code: "+385", name: "Croatia", iso: "hr", minlen: 10, maxlen: 12 },
  { code: "+53", name: "Cuba", iso: "cu", minlen: 9, maxlen: 11 },
  { code: "+357", name: "Cyprus", iso: "cy", minlen: 10, maxlen: 11 },
  { code: "+420", name: "Czech Republic", iso: "cz", minlen: 11, maxlen: 12 },
  { code: "+243", name: "Democratic Republic of Congo", iso: "cd", minlen: 10, maxlen: 12 },
  { code: "+45", name: "Denmark", iso: "dk", minlen: 10, maxlen: 10 },
  { code: "+253", name: "Djibouti", iso: "dj", minlen: 9, maxlen: 10 },
  { code: "+1-809", name: "Dominican Republic", iso: "do", minlen: 11, maxlen: 11 },
  { code: "+1-829", name: "Dominican Republic", iso: "do", minlen: 11, maxlen: 11 },
  { code: "+1-849", name: "Dominican Republic", iso: "do", minlen: 11, maxlen: 11 },
  { code: "+593", name: "Ecuador", iso: "ec", minlen: 10, maxlen: 11 },
  { code: "+20", name: "Egypt", iso: "eg", minlen: 11, maxlen: 12 },
  { code: "+503", name: "El Salvador", iso: "sv", minlen: 10, maxlen: 11 },
  { code: "+372", name: "Estonia", iso: "ee", minlen: 10, maxlen: 11 },
  { code: "+251", name: "Ethiopia", iso: "et", minlen: 11, maxlen: 12 },
  { code: "+679", name: "Fiji", iso: "fj", minlen: 9, maxlen: 10 },
  { code: "+358", name: "Finland", iso: "fi", minlen: 10, maxlen: 12 },
  { code: "+33", name: "France", iso: "fr", minlen: 11, maxlen: 11 },
  { code: "+241", name: "Gabon", iso: "ga", minlen: 9, maxlen: 10 },
  { code: "+220", name: "Gambia", iso: "gm", minlen: 9, maxlen: 10 },
  { code: "+995", name: "Georgia", iso: "ge", minlen: 11, maxlen: 12 },
  { code: "+49", name: "Germany", iso: "de", minlen: 11, maxlen: 13 },
  { code: "+233", name: "Ghana", iso: "gh", minlen: 11, maxlen: 12 },
  { code: "+30", name: "Greece", iso: "gr", minlen: 11, maxlen: 11 },
  { code: "+502", name: "Guatemala", iso: "gt", minlen: 10, maxlen: 11 },
  { code: "+509", name: "Haiti", iso: "ht", minlen: 10, maxlen: 11 },
  { code: "+504", name: "Honduras", iso: "hn", minlen: 10, maxlen: 11 },
  { code: "+852", name: "Hong Kong", iso: "hk", minlen: 10, maxlen: 11 },
  { code: "+36", name: "Hungary", iso: "hu", minlen: 10, maxlen: 11 },
  { code: "+354", name: "Iceland", iso: "is", minlen: 9, maxlen: 10 },
  { code: "+91", name: "India", iso: "in", minlen: 12, maxlen: 12 },
  { code: "+62", name: "Indonesia", iso: "id", minlen: 11, maxlen: 13 },
  { code: "+98", name: "Iran", iso: "ir", minlen: 11, maxlen: 12 },
  { code: "+964", name: "Iraq", iso: "iq", minlen: 11, maxlen: 12 },
  { code: "+353", name: "Ireland", iso: "ie", minlen: 10, maxlen: 12 },
  { code: "+972", name: "Israel", iso: "il", minlen: 11, maxlen: 12 },
  { code: "+39", name: "Italy", iso: "it", minlen: 11, maxlen: 13 },
  { code: "+1-876", name: "Jamaica", iso: "jm", minlen: 11, maxlen: 11 },
  { code: "+81", name: "Japan", iso: "jp", minlen: 11, maxlen: 12 },
  { code: "+962", name: "Jordan", iso: "jo", minlen: 10, maxlen: 11 },
  { code: "+7", name: "Kazakhstan", iso: "kz", minlen: 11, maxlen: 11 },
  { code: "+254", name: "Kenya", iso: "ke", minlen: 11, maxlen: 12 },
  { code: "+965", name: "Kuwait", iso: "kw", minlen: 10, maxlen: 11 },
  { code: "+996", name: "Kyrgyzstan", iso: "kg", minlen: 11, maxlen: 12 },
  { code: "+856", name: "Laos", iso: "la", minlen: 10, maxlen: 12 },
  { code: "+371", name: "Latvia", iso: "lv", minlen: 10, maxlen: 11 },
  { code: "+961", name: "Lebanon", iso: "lb", minlen: 10, maxlen: 11 },
  { code: "+218", name: "Libya", iso: "ly", minlen: 10, maxlen: 11 },
  { code: "+370", name: "Lithuania", iso: "lt", minlen: 10, maxlen: 11 },
  { code: "+352", name: "Luxembourg", iso: "lu", minlen: 9, maxlen: 12 },
  { code: "+60", name: "Malaysia", iso: "my", minlen: 10, maxlen: 12 },
  { code: "+960", name: "Maldives", iso: "mv", minlen: 9, maxlen: 10 },
  { code: "+223", name: "Mali", iso: "ml", minlen: 10, maxlen: 11 },
  { code: "+356", name: "Malta", iso: "mt", minlen: 10, maxlen: 10 },
  { code: "+52", name: "Mexico", iso: "mx", minlen: 11, maxlen: 13 },
  { code: "+976", name: "Mongolia", iso: "mn", minlen: 10, maxlen: 11 },
  { code: "+382", name: "Montenegro", iso: "me", minlen: 10, maxlen: 11 },
  { code: "+212", name: "Morocco", iso: "ma", minlen: 11, maxlen: 12 },
  { code: "+258", name: "Mozambique", iso: "mz", minlen: 11, maxlen: 12 },
  { code: "+95", name: "Myanmar", iso: "mm", minlen: 9, maxlen: 12 },
  { code: "+977", name: "Nepal", iso: "np", minlen: 11, maxlen: 12 },
  { code: "+31", name: "Netherlands", iso: "nl", minlen: 11, maxlen: 11 },
  { code: "+64", name: "New Zealand", iso: "nz", minlen: 10, maxlen: 12 },
  { code: "+234", name: "Nigeria", iso: "ng", minlen: 11, maxlen: 12 },
  { code: "+850", name: "North Korea", iso: "kp", minlen: 10, maxlen: 12 },
  { code: "+47", name: "Norway", iso: "no", minlen: 10, maxlen: 10 },
  { code: "+968", name: "Oman", iso: "om", minlen: 10, maxlen: 11 },
  { code: "+92", name: "Pakistan", iso: "pk", minlen: 11, maxlen: 12 },
  { code: "+507", name: "Panama", iso: "pa", minlen: 10, maxlen: 11 },
  { code: "+595", name: "Paraguay", iso: "py", minlen: 10, maxlen: 12 },
  { code: "+51", name: "Peru", iso: "pe", minlen: 10, maxlen: 12 },
  { code: "+63", name: "Philippines", iso: "ph", minlen: 11, maxlen: 12 },
  { code: "+48", name: "Poland", iso: "pl", minlen: 11, maxlen: 11 },
  { code: "+351", name: "Portugal", iso: "pt", minlen: 11, maxlen: 11 },
  { code: "+974", name: "Qatar", iso: "qa", minlen: 10, maxlen: 11 },
  { code: "+40", name: "Romania", iso: "ro", minlen: 11, maxlen: 11 },
  { code: "+7", name: "Russia", iso: "ru", minlen: 11, maxlen: 11 },
  { code: "+250", name: "Rwanda", iso: "rw", minlen: 11, maxlen: 12 },
  { code: "+966", name: "Saudi Arabia", iso: "sa", minlen: 11, maxlen: 12 },
  { code: "+221", name: "Senegal", iso: "sn", minlen: 11, maxlen: 12 },
  { code: "+381", name: "Serbia", iso: "rs", minlen: 10, maxlen: 12 },
  { code: "+65", name: "Singapore", iso: "sg", minlen: 10, maxlen: 10 },
  { code: "+421", name: "Slovakia", iso: "sk", minlen: 11, maxlen: 12 },
  { code: "+386", name: "Slovenia", iso: "si", minlen: 10, maxlen: 11 },
  { code: "+27", name: "South Africa", iso: "za", minlen: 11, maxlen: 11 },
  { code: "+82", name: "South Korea", iso: "kr", minlen: 11, maxlen: 12 },
  { code: "+34", name: "Spain", iso: "es", minlen: 11, maxlen: 11 },
  { code: "+94", name: "Sri Lanka", iso: "lk", minlen: 10, maxlen: 11 },
  { code: "+249", name: "Sudan", iso: "sd", minlen: 11, maxlen: 12 },
  { code: "+46", name: "Sweden", iso: "se", minlen: 10, maxlen: 12 },
  { code: "+41", name: "Switzerland", iso: "ch", minlen: 11, maxlen: 12 },
  { code: "+963", name: "Syria", iso: "sy", minlen: 10, maxlen: 12 },
  { code: "+886", name: "Taiwan", iso: "tw", minlen: 10, maxlen: 11 },
  { code: "+992", name: "Tajikistan", iso: "tj", minlen: 11, maxlen: 12 },
  { code: "+255", name: "Tanzania", iso: "tz", minlen: 11, maxlen: 12 },
  { code: "+66", name: "Thailand", iso: "th", minlen: 11, maxlen: 11 },
  { code: "+216", name: "Tunisia", iso: "tn", minlen: 10, maxlen: 11 },
  { code: "+90", name: "Turkey", iso: "tr", minlen: 11, maxlen: 12 },
  { code: "+993", name: "Turkmenistan", iso: "tm", minlen: 10, maxlen: 11 },
  { code: "+256", name: "Uganda", iso: "ug", minlen: 11, maxlen: 12 },
  { code: "+380", name: "Ukraine", iso: "ua", minlen: 11, maxlen: 12 },
  { code: "+971", name: "United Arab Emirates", iso: "ae", minlen: 10, maxlen: 12 },
  { code: "+44", name: "United Kingdom", iso: "gb", minlen: 11, maxlen: 12 },
  { code: "+1", name: "United States", iso: "us", minlen: 11, maxlen: 11 },
  { code: "+598", name: "Uruguay", iso: "uy", minlen: 10, maxlen: 11 },
  { code: "+998", name: "Uzbekistan", iso: "uz", minlen: 11, maxlen: 12 },
  { code: "+58", name: "Venezuela", iso: "ve", minlen: 11, maxlen: 12 },
  { code: "+84", name: "Vietnam", iso: "vn", minlen: 11, maxlen: 12 },
  { code: "+967", name: "Yemen", iso: "ye", minlen: 10, maxlen: 11 },
  { code: "+260", name: "Zambia", iso: "zm", minlen: 11, maxlen: 12 },
  { code: "+263", name: "Zimbabwe", iso: "zw", minlen: 10, maxlen: 12 }
];